/**
 * Seed de Citações de Exemplo (aforismos + citações de livros + filmes + ditos)
 *
 * Pré-carregados quando o usuário abre a extensão pela primeira vez.
 * Fase 1 (v0.2.0): suporte a tipo="aforismo" | tipo="citacao" | tipo="filme" | tipo="dito"
 * Fase 3 (v0.3.0): suporte a imagens[] e livrosRecomendados[]
 * Ver: docs/MANUAL_TECNICO.md §3.6
 */

const seedAforismos = [
  // ========== AFORISMOS (10) ==========

  {
    id: 'afor-1',
    tipo: 'aforismo',
    texto: 'Não é porque as coisas são difíceis que não ousamos; é porque não ousamos que elas são difíceis.',
    autor: 'Sêneca',
    obra: 'Cartas a Lucílio',
    epoca: 'c. 65 d.C.',
    anoReferencia: 65,
    anoPublicacao: 65,
    idiomaOriginal: null,
    textoOriginal: null,
    categoriaIds: ['cat-estoicismo', 'cat-acao'],
    tags: ['coragem', 'ação', 'superacao'],
    favorito: false,
    notas: '',
    leitura_completa: false,
    comentarios: [],
    imagens: [],
    livrosRecomendados: [
      {
        id: 'livro-1',
        titulo: 'Cartas a Lucílio',
        autor: 'Sêneca',
        isbn: '9788532926050',
        marketplace: 'amazon',
        urlAfiliado: 'https://amazon.com.br/Cartas-Lucílio-Sêneca/dp/8532926050',
        comoRelacionado: 'Obra original do aforismo',
        addedAt: new Date().toISOString(),
      },
      {
        id: 'livro-2',
        titulo: 'Meditações sobre o Estoicismo',
        autor: 'Pierre Hadot',
        isbn: '9788577609945',
        marketplace: 'skoob',
        urlAfiliado: 'https://www.skoob.com.br/livro/8577609945',
        comoRelacionado: 'Análise moderna da filosofia estoica de Sêneca',
        addedAt: new Date().toISOString(),
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  {
    id: 'afor-2',
    tipo: 'aforismo',
    texto: 'Você tem poder sobre sua mente — não sobre os eventos externos. Perceba isso e encontrará força.',
    autor: 'Marcus Aurelius',
    obra: 'Meditações',
    epoca: 'c. 161 d.C.',
    anoReferencia: 161,
    anoPublicacao: 161,
    idiomaOriginal: null,
    textoOriginal: null,
    categoriaIds: ['cat-estoicismo', 'cat-conhecimento'],
    tags: ['poder', 'mente', 'liberdade'],
    favorito: false,
    notas: '',
    leitura_completa: false,
    comentarios: [],
    imagens: [],
    livrosRecomendados: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  {
    id: 'afor-3',
    tipo: 'aforismo',
    texto: 'A morte não nos importa; quando existimos, a morte não existe; quando a morte existe, não existimos.',
    autor: 'Montaigne',
    obra: 'Ensaios',
    epoca: '1580',
    anoReferencia: 1580,
    anoPublicacao: 1580,
    idiomaOriginal: null,
    textoOriginal: null,
    categoriaIds: ['cat-morte', 'cat-conhecimento'],
    tags: ['morte', 'existencia', 'sabedoria'],
    favorito: false,
    notas: '',
    leitura_completa: false,
    comentarios: [],
    imagens: [],
    livrosRecomendados: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  {
    id: 'afor-4',
    tipo: 'aforismo',
    texto: 'Não são as coisas que perturbam os homens, mas as suas opiniões sobre as coisas.',
    autor: 'Epicteto',
    obra: 'Enchiridion',
    epoca: 'c. 50 d.C.',
    anoReferencia: 50,
    anoPublicacao: 50,
    idiomaOriginal: 'grego',
    textoOriginal: 'Ἐστὶν αὕτη ἡ σκοπευτική…',
    categoriaIds: ['cat-estoicismo', 'cat-conhecimento'],
    tags: ['opiniao', 'perturbacao', 'controle'],
    favorito: false,
    notas: 'Citada frequentemente por Marco Aurélio.',
    leitura_completa: false,
    comentarios: [],
    imagens: [],
    livrosRecomendados: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  {
    id: 'afor-5',
    tipo: 'aforismo',
    texto: 'O coração tem suas razões que a razão desconhece.',
    autor: 'Pascal',
    obra: 'Pensées',
    epoca: '1670',
    anoReferencia: 1670,
    anoPublicacao: 1670,
    idiomaOriginal: 'francês',
    textoOriginal: 'Le cœur a ses raisons que la raison ne connaît point.',
    categoriaIds: ['cat-conhecimento', 'cat-amor'],
    tags: ['coracao', 'razao', 'emocao'],
    favorito: false,
    notas: '',
    leitura_completa: false,
    comentarios: [],
    imagens: [],
    livrosRecomendados: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  {
    id: 'afor-6',
    tipo: 'aforismo',
    texto: 'Nós condenamos nos outros os vícios que não temos.',
    autor: 'La Rochefoucauld',
    obra: 'Máximas',
    epoca: '1665',
    anoReferencia: 1665,
    anoPublicacao: 1665,
    idiomaOriginal: 'francês',
    textoOriginal: 'Nous condamnons chez les autres les vices que nous n\'avons pas.',
    categoriaIds: ['cat-moral', 'cat-conhecimento'],
    tags: ['hipocrisia', 'critica', 'virtude'],
    favorito: false,
    notas: '',
    leitura_completa: false,
    comentarios: [],
    imagens: [],
    livrosRecomendados: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  {
    id: 'afor-7',
    tipo: 'aforismo',
    texto: 'O que não me mata, me fortalece.',
    autor: 'Friedrich Nietzsche',
    obra: 'Crepúsculo dos Ídolos',
    epoca: '1888',
    anoReferencia: 1888,
    anoPublicacao: 1888,
    idiomaOriginal: 'alemão',
    textoOriginal: 'Was mich nicht umbringt, macht mich stärker.',
    categoriaIds: ['cat-virtude', 'cat-acao'],
    tags: ['forca', 'adversidade', 'crescimento'],
    favorito: false,
    notas: '',
    leitura_completa: false,
    comentarios: [],
    imagens: [],
    livrosRecomendados: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  {
    id: 'afor-8',
    tipo: 'aforismo',
    texto: 'Ninguém entra duas vezes no mesmo rio.',
    autor: 'Heráclito',
    obra: 'Fragmentos',
    epoca: 'c. 500 a.C.',
    anoReferencia: -500,
    anoPublicacao: -500,
    idiomaOriginal: 'grego',
    textoOriginal: 'Οὐ γὰρ δύο χρόα τῷ αὐτῷ ποταμῷ ἐμβαίνειν…',
    categoriaIds: ['cat-tempo', 'cat-conhecimento'],
    tags: ['fluxo', 'mudanca', 'natureza'],
    favorito: false,
    notas: '',
    leitura_completa: false,
    comentarios: [],
    imagens: [],
    livrosRecomendados: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  {
    id: 'afor-9',
    tipo: 'aforismo',
    texto: 'Quando se conhece a si mesmo, não há o que temer; quando se conhece o outro, a vitória é segura.',
    autor: 'Confúcio',
    obra: 'Analectos',
    epoca: 'c. 500 a.C.',
    anoReferencia: -500,
    anoPublicacao: -500,
    idiomaOriginal: 'chinês',
    textoOriginal: null,
    categoriaIds: ['cat-conhecimento', 'cat-acao'],
    tags: ['autoconhecimento', 'vitoria', 'sabedoria'],
    favorito: false,
    notas: '',
    leitura_completa: false,
    comentarios: [],
    imagens: [],
    livrosRecomendados: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  {
    id: 'afor-10',
    tipo: 'aforismo',
    texto: 'O homem pode fazer o que ele quer, mas ele não pode querer o que quer.',
    autor: 'Arthur Schopenhauer',
    obra: 'Ensaio sobre o Livre Arbítrio',
    epoca: '1839',
    anoReferencia: 1839,
    anoPublicacao: 1839,
    idiomaOriginal: 'alemão',
    textoOriginal: 'Der Mensch kann tun, was er will; aber er kann nicht wollen, was er will.',
    categoriaIds: ['cat-conhecimento', 'cat-moral'],
    tags: ['livre-arbitrio', 'determinismo', 'vontade'],
    favorito: false,
    notas: '',
    leitura_completa: false,
    comentarios: [],
    imagens: [],
    livrosRecomendados: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ========== CITAÇÕES DE LIVROS (6) ==========

  {
    id: 'cit-1',
    tipo: 'citacao',
    texto: 'Era o melhor dos tempos, era o pior dos tempos, era a idade da sabedoria, era a idade da loucura...',
    contexto: 'Abertura do romance, estabelecendo o contraste fundamental da época',
    autor: 'Charles Dickens',
    obra: 'Um Conto de Duas Cidades',
    pagina: 1,
    edicao: 'Penguin Classics, 2003',
    anoPublicacao: 1859,
    anoReferencia: 1859,
    generoLiterario: 'romance',
    idiomaOriginal: 'inglês',
    textoOriginal: 'It was the best of times, it was the worst of times...',
    categoriaIds: ['cat-tempo', 'cat-conhecimento'],
    tags: ['contraste', 'abertura', 'dualidade'],
    favorito: false,
    notas: 'Uma das aberturas mais famosas da literatura em inglês',
    leitura_completa: false,
    comentarios: [],
    imagens: [],
    livrosRecomendados: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  {
    id: 'cit-2',
    tipo: 'citacao',
    texto: 'Era como se o coração tivesse saído do peito e pousado numa árvore distante, vendo-se a si mesmo de longe.',
    contexto: 'Capítulo de reflexão do protagonista sobre seu amor perdido',
    autor: 'Machado de Assis',
    obra: 'Dom Casmurro',
    pagina: 45,
    edicao: '1ª edição, 1899',
    anoPublicacao: 1899,
    anoReferencia: 1899,
    generoLiterario: 'romance',
    idiomaOriginal: null,
    textoOriginal: null,
    categoriaIds: ['cat-amor', 'cat-conhecimento'],
    tags: ['coracao', 'distancia', 'reflexao'],
    favorito: false,
    notas: 'Prosa psicológica de Machado',
    leitura_completa: false,
    comentarios: [],
    imagens: [],
    livrosRecomendados: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  {
    id: 'cit-3',
    tipo: 'citacao',
    texto: 'O sertão é grande. Dentro dele cabem muitos sertões.',
    contexto: 'Abertura que estabelece a dimensão geográfica e metafórica do sertão',
    autor: 'Guimarães Rosa',
    obra: 'Grande Sertão: Veredas',
    pagina: 1,
    edicao: '1ª edição, 1956',
    anoPublicacao: 1956,
    anoReferencia: 1956,
    generoLiterario: 'romance',
    idiomaOriginal: null,
    textoOriginal: null,
    categoriaIds: ['cat-conhecimento', 'cat-tempo'],
    tags: ['sertao', 'espaco', 'poesia'],
    favorito: false,
    notas: 'Rosa revitaliza o português com inovações linguísticas',
    leitura_completa: false,
    comentarios: [],
    imagens: [],
    livrosRecomendados: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  {
    id: 'cit-4',
    tipo: 'citacao',
    texto: 'Todos os animais são iguais, mas alguns animais são mais iguais do que outros.',
    contexto: 'A corrupção do sétimo mandamento na Fazenda Animal, simbolizando a perversão de ideais revolucionários',
    autor: 'George Orwell',
    obra: 'A Revolução dos Bichos',
    pagina: 108,
    edicao: 'Penguin Classics, 1945',
    anoPublicacao: 1945,
    anoReferencia: 1945,
    generoLiterario: 'fábula',
    idiomaOriginal: 'inglês',
    textoOriginal: 'All animals are equal, but some animals are more equal than others.',
    categoriaIds: ['cat-politica', 'cat-moral'],
    tags: ['igualdade', 'poder', 'corrupcao'],
    favorito: false,
    notas: 'Alegoria sobre a Revolução Russa e o totalitarismo',
    leitura_completa: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  {
    id: 'cit-5',
    tipo: 'citacao',
    texto: 'Primeira eu quero estar segura de que estou realmente respirando e que esta não é uma morte diferente.',
    contexto: 'Morna refletindo sobre a realidade da escravidão e da morte',
    autor: 'Aluísio Azevedo',
    obra: 'O Cortiço',
    pagina: 78,
    edicao: '1ª edição, 1890',
    anoPublicacao: 1890,
    anoReferencia: 1890,
    generoLiterario: 'romance',
    idiomaOriginal: null,
    textoOriginal: null,
    categoriaIds: ['cat-morte', 'cat-conhecimento'],
    tags: ['existencia', 'liberdade', 'escravidao'],
    favorito: false,
    notas: 'Romance naturalista focado em personagens marginalizados',
    leitura_completa: false,
    comentarios: [],
    imagens: [],
    livrosRecomendados: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  {
    id: 'cit-6',
    tipo: 'citacao',
    texto: 'Ela não possuía o que se chama de beleza, mas tinha aquilo que é muito mais: graça.',
    contexto: 'Descrição física da protagonista Jane, enfatizando qualidades interiores',
    autor: 'Charlotte Brontë',
    obra: 'Jane Eyre',
    pagina: 89,
    edicao: 'Penguin Classics, 2006',
    anoPublicacao: 1847,
    anoReferencia: 1847,
    generoLiterario: 'romance',
    idiomaOriginal: 'inglês',
    textoOriginal: 'She is not pretty; but she has a grace of her own.',
    categoriaIds: ['cat-conhecimento', 'cat-amor'],
    tags: ['beleza', 'graça', 'interioridade'],
    favorito: false,
    notas: 'Charlotte Brontë desafia os padrões de beleza feminina',
    leitura_completa: false,
    comentarios: [],
    imagens: [],
    livrosRecomendados: [],
    comentarios: [],
    imagens: [],
    livrosRecomendados: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ========== FILMES (1) ==========

  {
    id: 'film-1',
    tipo: 'filme',
    texto: 'You\'re a wizard, Harry.',
    contexto: 'Revelação de Hagrid a Harry Potter sobre seu verdadeiro destino',
    autor: 'Hagrid (Robbie Coltrane)',
    obra: 'Harry Potter and the Philosopher\'s Stone',
    pagina: null,
    edicao: 'Edição teatral',
    anoPublicacao: 2001,
    anoReferencia: 2001,
    generoLiterario: 'fantasia',
    idiomaOriginal: 'inglês',
    textoOriginal: null,
    categoriaIds: ['cat-conhecimento', 'cat-acao'],
    tags: ['destino', 'magia', 'descoberta'],
    favorito: false,
    notas: 'Cena icônica que marca o início da jornada de Harry',
    leitura_completa: false,
    comentarios: [],
    imagens: [],
    livrosRecomendados: [],
    comentarios: [],
    imagens: [],
    livrosRecomendados: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ========== DITOS POPULARES (1) ==========

  {
    id: 'dito-1',
    tipo: 'dito',
    texto: 'Deus ajuda quem cedo madruga.',
    contexto: 'Provérbio sobre o valor da diligência e da madrugada',
    autor: 'Sabedoria popular',
    obra: 'Tradição oral',
    pagina: null,
    edicao: null,
    anoPublicacao: null,
    anoReferencia: null,
    generoLiterario: 'provérbio',
    idiomaOriginal: null,
    textoOriginal: null,
    categoriaIds: ['cat-ditos', 'cat-acao', 'cat-conhecimento'],
    tags: ['trabalho', 'virtude', 'diligência'],
    favorito: false,
    notas: 'Dito popular muito comum na cultura portuguesa e brasileira',
    leitura_completa: false,
    comentarios: [],
    imagens: [],
    livrosRecomendados: [],
    comentarios: [],
    imagens: [],
    livrosRecomendados: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
