/**
 * Seed de Aforismos de Exemplo (~10 aforismos de domínio público)
 *
 * Pré-carregados quando o usuário abre a extensão pela primeira vez.
 * Cada um demonstra múltiplas categorias e tags.
 * Ver: docs/MANUAL_TECNICO.md §3.6
 */

const seedAforismos = [
  {
    id: 'afor-1',
    texto: 'Não é porque as coisas são difíceis que não ousamos; é porque não ousamos que elas são difíceis.',
    autor: 'Sêneca',
    obra: 'Cartas a Lucílio',
    epoca: 'c. 65 d.C.',
    anoReferencia: 65,
    idiomaOriginal: null,
    textoOriginal: null,
    categoriaIds: ['cat-estoicismo', 'cat-acao'],
    tags: ['coragem', 'ação', 'superacao'],
    favorito: false,
    notas: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  {
    id: 'afor-2',
    texto: 'Você tem poder sobre sua mente — não sobre os eventos externos. Perceba isso e encontrará força.',
    autor: 'Marcus Aurelius',
    obra: 'Meditações',
    epoca: 'c. 161 d.C.',
    anoReferencia: 161,
    idiomaOriginal: null,
    textoOriginal: null,
    categoriaIds: ['cat-estoicismo', 'cat-conhecimento'],
    tags: ['poder', 'mente', 'liberdade'],
    favorito: false,
    notas: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  {
    id: 'afor-3',
    texto: 'A morte não nos importa; quando existimos, a morte não existe; quando a morte existe, não existimos.',
    autor: 'Montaigne',
    obra: 'Ensaios',
    epoca: '1580',
    anoReferencia: 1580,
    idiomaOriginal: null,
    textoOriginal: null,
    categoriaIds: ['cat-morte', 'cat-conhecimento'],
    tags: ['morte', 'existencia', 'sabedoria'],
    favorito: false,
    notas: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  {
    id: 'afor-4',
    texto: 'Não são as coisas que perturbam os homens, mas as suas opiniões sobre as coisas.',
    autor: 'Epicteto',
    obra: 'Enchiridion',
    epoca: 'c. 50 d.C.',
    anoReferencia: 50,
    idiomaOriginal: 'grego',
    textoOriginal: 'Ἐστὶν αὕτη ἡ σκοπευτική…',
    categoriaIds: ['cat-estoicismo', 'cat-conhecimento'],
    tags: ['opiniao', 'perturbacao', 'controle'],
    favorito: false,
    notas: 'Citada frequentemente por Marco Aurélio.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  {
    id: 'afor-5',
    texto: 'O coração tem suas razões que a razão desconhece.',
    autor: 'Pascal',
    obra: 'Pensées',
    epoca: '1670',
    anoReferencia: 1670,
    idiomaOriginal: 'francês',
    textoOriginal: 'Le cœur a ses raisons que la raison ne connaît point.',
    categoriaIds: ['cat-conhecimento', 'cat-amor'],
    tags: ['coracao', 'razao', 'emocao'],
    favorito: false,
    notas: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  {
    id: 'afor-6',
    texto: 'Nós condenamos nos outros os vícios que não temos.',
    autor: 'La Rochefoucauld',
    obra: 'Máximas',
    epoca: '1665',
    anoReferencia: 1665,
    idiomaOriginal: 'francês',
    textoOriginal: 'Nous condamnons chez les autres les vices que nous n\'avons pas.',
    categoriaIds: ['cat-moral', 'cat-conhecimento'],
    tags: ['hipocrisia', 'critica', 'virtude'],
    favorito: false,
    notas: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  {
    id: 'afor-7',
    texto: 'O que não me mata, me fortalece.',
    autor: 'Friedrich Nietzsche',
    obra: 'Crepúsculo dos Ídolos',
    epoca: '1888',
    anoReferencia: 1888,
    idiomaOriginal: 'alemão',
    textoOriginal: 'Was mich nicht umbringt, macht mich stärker.',
    categoriaIds: ['cat-virtude', 'cat-acao'],
    tags: ['forca', 'adversidade', 'crescimento'],
    favorito: false,
    notas: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  {
    id: 'afor-8',
    texto: 'Ninguém entra duas vezes no mesmo rio.',
    autor: 'Heráclito',
    obra: 'Fragmentos',
    epoca: 'c. 500 a.C.',
    anoReferencia: -500,
    idiomaOriginal: 'grego',
    textoOriginal: 'Οὐ γὰρ δύο χρόα τῷ αὐτῷ ποταμῷ ἐμβαίνειν…',
    categoriaIds: ['cat-tempo', 'cat-conhecimento'],
    tags: ['fluxo', 'mudanca', 'natureza'],
    favorito: false,
    notas: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  {
    id: 'afor-9',
    texto: 'Quando se conhece a si mesmo, não há o que temer; quando se conhece o outro, a vitória é segura.',
    autor: 'Confúcio',
    obra: 'Analectos',
    epoca: 'c. 500 a.C.',
    anoReferencia: -500,
    idiomaOriginal: 'chinês',
    textoOriginal: null,
    categoriaIds: ['cat-conhecimento', 'cat-acao'],
    tags: ['autoconhecimento', 'vitoria', 'sabedoria'],
    favorito: false,
    notas: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  {
    id: 'afor-10',
    texto: 'O homem pode fazer o que ele quer, mas ele não pode querer o que quer.',
    autor: 'Arthur Schopenhauer',
    obra: 'Ensaio sobre o Livre Arbítrio',
    epoca: '1839',
    anoReferencia: 1839,
    idiomaOriginal: 'alemão',
    textoOriginal: 'Der Mensch kann tun, was er will; aber er kann nicht wollen, was er will.',
    categoriaIds: ['cat-conhecimento', 'cat-moral'],
    tags: ['livre-arbitrio', 'determinismo', 'vontade'],
    favorito: false,
    notas: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
